### ISSUE TITLE
关于数据集相关的问题 discussion about this project

### ISSUE THREAD

**Issue by HelenaLJQ** [bytesc/Image-Recognition-system#1]
您好，我还是有几个问题想问一下。
问题一：.nii格式的数据现在应该怎么下载呢？因为我按照正常方式框选之后，现在是不可以直接选择NIFTI格式数据的，对于原始图像的话，下载下来是dcm格式，所以想问问您是怎么下载的呢？
问题二：您认为如果用预处理过的数据对该模型进行训练，会不会对分类准确率产生积极的影响呢？
问题三：如果需要预处理的话，您觉得应该进行什么样的步骤呢？最好就是最后可以把预处理模块嵌入到模型当中，然后，上传原始图像就可以进行预测，只不过或许也会执行预处理的步骤，可以执行，也可以不执行这种，您觉得是否可行呢？
问题四：您在创建该模型的时候有没有考虑过就是说，把每一个人作为一个主体，然后，针对他前后上传的两次或者几次MRI然后来判断该患者是否是进展型患者呢？
问题五：针对其他权威论文里面的数据集，就是类别上会不会有区别呢？比如说，该项目里面是把患者分成了5类，如果使用多的数据集的话，数据量是变多了，但是不知道在类别上是否可以对应呢？这个问题我也不太清楚，所以会有一点点疑问哈~抱歉，我问题可能有点多呢~
问题六：您觉得做阿尔茨海默病分类网站的话，可以做什么事情对其进行改进吗~因为我们需要有创新点~想问问您的想法~
问题七：您觉得目前您存在的问题应该怎么解决呢？
然后就是，因为我也是做阿尔茨海默病的分类，这方面的同行的人也比较少，而且由于我是专硕，所以最后也是需要做个网站出来，所以您介不介意在您的项目基础上我进行改进呢？或者说，可以有机会跟你一起实现这个事情吗？

**Comment by bytesc** [comment]
问题一：
<img width="836" alt="Snipaste_2023-12-06_21-55-30" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/4118ae96-4ce1-4bab-b207-c5f150f0237a">

<img width="407" alt="Snipaste_2023-12-06_21-54-34" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/d7f0da08-296e-4a5d-aea3-115c07db281e">

**Comment by bytesc** [comment]
问题二：
预处理数据通常会对模型的性能产生积极的影响。预处理可以帮助减少噪声，提高数据的质量，使模型能够更好地学习和识别图像中的模式。这可能会提高模型的分类准确率。

**Comment by bytesc** [comment]
@HelenaLJQ 
问题三：
这是完全可行的。预处理步骤可能包括去噪，标准化，以及其他增强图像质量的技术。这些步骤可以作为模型的一部分，当上传原始图像进行预测时，可以选择是否执行预处理步骤。这种灵活性可以让您根据需要来优化模型的性能。我认为这是一个很好的策略，可以帮助提高模型的性能和准确性。

**Comment by bytesc** [comment]
问题五：
> 针对其他权威论文里面的数据集，就是类别上会不会有区别呢？比如说，该项目里面是把患者分成了5类，如果使用多的数据集的话，数据量是变多了，但是不知道在类别上是否可以对应呢？

` ADNI, AIBL, NACC, NIFD, OASIS, PPMI, FHS, LBDSU` 等数据集我并没有全部获取，`AD`, `MCI` ,`CN`,`EMCI`,`LMCI` 是较为通用的临床诊断划分。至少`AD`，`CN` 两类是一定有的。

**Comment by bytesc** [comment]
问题六：
> 您觉得做阿尔茨海默病分类网站的话，可以做什么事情对其进行改进吗因为我们需要有创新点想问问您的想法~

从网站创新点角度：
- 使用交互式工具：开发一些交互式工具，帮助用户进行自我评估和检测风险。这些工具可以是简单的问卷或测试，帮助用户了解自己的症状、风险因素和可能的诊断。
- 提供社区支持平台：创建一个社区支持平台，让患者、照顾者和专业人士能够互相交流、分享经验和提供支持。这样的平台可以包括在线论坛、聊天室或讨论板，促进用户之间的互动和互助。
- 整合科学研究和最新进展：定期更新网站，以包括最新的科学研究、突破性治疗和阿尔茨海默病管理的最新进展。这样，您的网站将成为用户获取可靠信息和前沿知识的首选来源。

**Comment by bytesc** [comment]
@HelenaLJQ 
> 然后就是，因为我也是做阿尔茨海默病的分类，这方面的同行的人也比较少，而且由于我是专硕，所以最后也是需要做个网站出来，所以您介不介意在您的项目基础上我进行改进呢？或者说，可以有机会跟你一起实现这个事情吗？

项目使用 `MIT` 开源协议，欢迎在遵守开源协议的前提下在项目基础上进行改进，引用，复用。

另外，”这方面的同行的人“ 其实并不少，实际上由于`ADNI`数据集获取相对便利，这方面的研究是非常多的，虽然高质量的研究可能不多。项目发布以来，也已经有很多研究同行通过这个仓库找到我了😂 。

关于一起实现网站的相关事宜，我会通过您的邮箱回复。

**Comment by bytesc** [comment]
<img width="899" alt="Snipaste_2024-01-05_16-45-41" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/b98d5936-ecb5-4548-9e1d-7ed2e6b3cdf2">
<img width="880" alt="Snipaste_2024-01-05_16-46-43" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/e7239cf7-344d-40da-bb74-b1b5f32ac94b">
<img width="894" alt="Snipaste_2024-01-05_16-47-17" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/501ae359-3854-4ccc-b2b0-5973d5cb1ecb">

**Comment by kpdy7nsd5-ai** [comment]
你好，请问这个web是根据某个论文建立的吗，如果是的话你有相关论文的链接吗

**Comment by HelenaLJQ** [comment]
不是根据某个论文建立的

**Comment by PG13George** [comment]
同样想问一下 这个project是基于某个论文的复现吗？

**Comment by HelenaLJQ** [comment]
不是



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Frank ***@***.***&gt;
发送时间: 2026年1月9日 05:58
收件人: bytesc/Image-Recognition-system ***@***.***&gt;
抄送: HelenaLJQ ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [bytesc/Image-Recognition-system] 关于数据集相关的问题 discussion about this project (Issue #1)



PG13George left a comment (bytesc/Image-Recognition-system#1)
 
同样想问一下 这个project是基于某个论文的复现吗？
