### ISSUE TITLE
数据集获取渠道的问题

### ISSUE THREAD

**Issue by KobeDavid** [bytesc/Image-Recognition-system#2]
你好，在IDA网络里面怎么下载数据集呢，就是找不到

**Comment by bytesc** [comment]
https://adni.loni.usc.edu/data-samples/access-data/

@KobeDavid

**Comment by KobeDavid** [comment]
就是我登进去了，不知道怎么下载

**Comment by bytesc** [comment]
<img width="505" alt="Snipaste_2024-01-05_09-11-29" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/dc741eb9-7db2-4981-a963-e9f0a5dd1fb3">
@KobeDavid

**Comment by KobeDavid** [comment]
![Uploading image.png…]()
我这里怎么没得ADNI

**Comment by bytesc** [comment]
<img width="328" alt="Snipaste_2024-01-05_11-30-03" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/35ae4ff1-3895-4228-9464-95a11dcc81b6">

你的图片没有上传成功 @KobeDavid

**Comment by KobeDavid** [comment]
就是我的select里面没有ADNI

**Comment by KobeDavid** [comment]
你有那个train.py运行的时，结果的图片吗？

**Comment by bytesc** [comment]
训练时，终端显示`损失`, `准确率`等数据。同时输出到`./logs.csv`文件。

**Comment by KobeDavid** [comment]
你运行时的终端显示的数据，有图片吗？./log.csv文件可以发一下吗？ 那个数据下载，要个几天才能通过下载

**Comment by bytesc** [comment]
你可以先使用我提供的数据集样例，测试训练程序是否能运行。
https://github.com/bytesc/lqdata
我的项目里也包含了训练好的模型，如果你需要进一步训练，可以下载完整数据集。
`./log.csv` 每次运行结果都不一样，我的运行结果和截图没有参考意义。

**Comment by bytesc** [comment]
<img width="488" alt="Snipaste_2024-01-05_15-39-08" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/c2fd5748-de26-4b47-9ded-1c58dc38aae4">

**Comment by KobeDavid** [comment]
RuntimeError: Parent directory ./model_save does not exist.这个错误是怎么解决

**Comment by KobeDavid** [comment]
这篇论文有吗，可以发一下不

**Comment by bytesc** [comment]
新建`./model_save`文件夹。
参考论文在`readme`里有写。

**Comment by KobeDavid** [comment]
那论文在哪里下载

**Comment by bytesc** [comment]
complete
