### ISSUE TITLE
数据集格式问题

### ISSUE THREAD

**Issue by pengpengcdx** [bytesc/Image-Recognition-system#3]
你好，请问一下这个项目是否必须使用nii格式的数据集，如果是的话，那么怎么才可以在Adni网站上下载呢，我自己去下载只下载得到一些图片，没有这个格式的文件

**Comment by bytesc** [comment]
1. 关于数据集下载：https://adni.loni.usc.edu/data-samples/access-data/ 需要申请等待 adni 审批。
2. mri扫描得到的是三维灰度图（X*X*X*1），例如`.nii`格式。图片（例如jpg）是二维的，不满足诊断需求。
3. 我在 https://github.com/bytesc/lqdata 提供了少量测试数据集样例。

**Comment by pengpengcdx** [comment]
我已经通过审核了，按照您回答别的议题的方法下载得到的只有普通图片格式而不是nii格式。请问一下这个问题是怎么回事呢

**Comment by bytesc** [comment]
<img width="899" alt="Snipaste_2024-01-05_16-45-41" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/be52787a-2646-488c-a461-b28b212dcb8b">
<img width="880" alt="Snipaste_2024-01-05_16-46-43" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/ac921903-2beb-49e4-8d83-8f626aabd6d0">
<img width="894" alt="Snipaste_2024-01-05_16-47-17" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/218ebac8-c2a9-4383-8ea4-0bd193f40cd3">

**Comment by pengpengcdx** [comment]
我的是这个样子的，数据那里是ADNIDOD，请问是因为我申请数据时出问题了吗，而且我的数据好像跟您的比起来少了好多![mmexport1704465186201.png](https://github.com/bytesc/Image-Recognition-system/assets/74348249/7e5ca1b0-3c72-4bbf-994d-240ff625507a)

![mmexport1704465183034.png](https://github.com/bytesc/Image-Recognition-system/assets/74348249/36e40e28-5559-4ca7-83f8-62ea74716613)

**Comment by pengpengcdx** [comment]
我下载的nii数据进行测试，出现了这样的问题。应该是我数据集不对的原因，请问一下申请的时候有什么注意事项吗？!![mmexport1704514107375.png](https://github.com/bytesc/Image-Recognition-system/assets/74348249/a3be0db9-b75c-49db-a9e8-5a45e965db29)

**Comment by bytesc** [comment]
nii是三维灰度图，应该是256x256x256x1。四维的张量。你上传的这个似乎是三维的张量。你可以打印输出你的nii图像的张量的shape检查。

**Comment by bytesc** [comment]
其实你下载的什么无关紧要，最终输入的时候处理成三维灰度图就行。

**Comment by pengpengcdx** [comment]
是的，下载的数据集的shape好像不是很对，但是找不到正确的数据集下载方法了

**Comment by pengpengcdx** [comment]
可是下载数据不对的话，训练也会有问题的

**Comment by bytesc** [comment]
只要数据信息内容有效，你可以处理成想要的格式。当然，你也可以修改模型和程序对其它格式和形式的数据进行适配。训练有问题是什么意思？

**Comment by pengpengcdx** [comment]
就是我是担心我下载的数据是有错误的，因为我发现官网有很多其他症状的数据，在看到您图片里是ANDI而且还有万这个量级的数据，但我是ANDIDOD且只有几百个数据的时候，就一直在怀疑是不是我的数据集申请有问题

**Comment by bytesc** [comment]
有可能，我也不是很清楚adni官方是如何授权数据的。使用edu邮箱，标注尽可能明确科研用途可能会更好。

**Comment by pengpengcdx** [comment]
好的，我现在重新申请一下，可以麻烦一下您帮忙看一下申请的是那一些数据吗，我第一次申请的时候只勾选了带有阿尔茨海默的相关选项

**Comment by bytesc** [comment]
complete

**Comment by bytesc** [comment]
complete

**Comment by 619135593** [comment]
> 可是下载数据不对的话，训练也会有问题的

有关数据下载，你会了吗

**Comment by pengpengcdx** [comment]
大概明白了

**Comment by 619135593** [comment]
是否可以加个微信，教教我



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月20日(周六) 晚上6:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bytesc/Image-Recognition-system] 数据集格式问题 (Issue #3)




 
大概明白了

**Comment by pengpengcdx** [comment]
可以

**Comment by 619135593** [comment]
我微信号：ZZL18720899652



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月20日(周六) 晚上6:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bytesc/Image-Recognition-system] 数据集格式问题 (Issue #3)




 
可以
