### ISSUE TITLE
关于网页使用自己的nii图片上传的问题

### ISSUE THREAD

**Issue by pengpengcdx** [bytesc/Image-Recognition-system#4]
请问web界面使用自己图片上传的功能，上传nii图片时，报维度错误，是因为上传的格式不是nii的错误吗，还是nii的数据不对的问题呢。
提交的时候ai诊断结果是可以正确的识别的，但是查看的时候就会出现维度的错误
![image](https://github.com/bytesc/Image-Recognition-system/assets/74348249/3de670f1-546e-4ad7-a39f-173b2277224f)
![image](https://github.com/bytesc/Image-Recognition-system/assets/74348249/3bee2cb3-d0f5-4cfc-8ac9-0db354c8f55b)

**Comment by bytesc** [comment]
<img width="524" alt="Snipaste_2024-01-20_11-13-19" src="https://github.com/bytesc/Image-Recognition-system/assets/103081365/8e2f8d1e-9c96-475e-82d9-1863873d84e0">

`.nii`是三维灰度图，也就是四维tensor，例如（256x256x256x1）

**Comment by bytesc** [comment]
你要上传的不是二维图片，mri图像是三维扫描。二维图片是肯定不合适的。

**Comment by pengpengcdx** [comment]
所以是上传的时候要处理一下nii文件吗，还是直接上传png图片呢

**Comment by bytesc** [comment]
需要上传，三维灰度图`.nii`。`.png`是二维平面图。png图片肯定是不行的。

**Comment by pengpengcdx** [comment]
噢噢，明白了，所以只需要再处理一下nii文件，变成三围就大概可以了吧

**Comment by bytesc** [comment]
![W671thSU2iR8HaE6P35gplhc5OgWVRng](https://github.com/bytesc/Image-Recognition-system/assets/103081365/4e758352-86c3-45a0-acf1-5a77f1a85e43)
![turv3AwegqTMDskgfYmRsipmheypEn56](https://github.com/bytesc/Image-Recognition-system/assets/103081365/9629d856-3b85-4852-92b8-c460a713fd8a)

我发现你上传了很多类似这样的二维图片，这样信息量是不足的。需要三维的医学影像。

**Comment by pengpengcdx** [comment]
我上传的是nii格式的文件呀，这个不是三维灰度图吗

**Comment by bytesc** [comment]
这个是二维的。三维图，是指x，y，z加上灰度。一共四维度的tensor。

**Comment by pengpengcdx** [comment]
噢噢，我是直接在官网上下载的nii文件，原来还有这个说法，受教了。那请问怎么下载三维图呢

**Comment by bytesc** [comment]
https://github.com/bytesc/Image-Recognition-system/issues/1

这是下载数据集的方法。
由于adni改变了nii数据的格式，导致新版的数据适配确实有问题，我对程序做出了最新的修改。
https://github.com/bytesc/Image-Recognition-system/commit/75ff551c34726cbc128a5c6371976a7a91537618

**Comment by bytesc** [comment]
complete
