### ISSUE TITLE
在ADNI下载数据部分出现的问题

### ISSUE THREAD

**Issue by pengpengcdx** [bytesc/Image-Recognition-system#5]
在下载数据过程中，发现visit属性中，部分值为bl的会出现图片的维度问题。
报的错如下：RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1600 and 4800x128)
[ADNI_003_S_0907_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070501171753634_S19728_I52781.zip](https://github.com/bytesc/Image-Recognition-system/files/14007588/ADNI_003_S_0907_MR_MPR__GradWarp__B1_Correction__N3__Scaled_Br_20070501171753634_S19728_I52781.zip)
这个文件是测试出现问题的nii文件。请问一下，下载数据的过程中，对数据的具体要求都有哪些呢
![image](https://github.com/bytesc/Image-Recognition-system/assets/74348249/aaa8caa9-bd45-41df-8d21-b2d6478275a3)
![image](https://github.com/bytesc/Image-Recognition-system/assets/74348249/ab7e92a8-7759-4dee-9df1-04554ce9fb3a)

**Comment by bytesc** [comment]
`.nii` (NIFTI)格式，(255x256x*)的大小。
