### ISSUE TITLE
Data issues

### ISSUE THREAD

**Issue by Yyutou** [bytesc/Image-Recognition-system#7]
How to download ADNI datasets,l already have access to visit,but l dont know how to use or select the "Advanced search" to choose the suitable images.

如何从ADNI官网下载数据，已经获取相关下载权限，但不知道如何选择检索条件获取数据图片
![屏幕截图 2024-03-14 125635](https://github.com/bytesc/Image-Recognition-system/assets/96705800/20b7c50f-b30b-4228-a333-40465b475669)

**Comment by bytesc** [comment]
#3

**Comment by 619135593** [comment]
> How to download ADNI datasets,l already have access to visit,but l dont know how to use or select the "Advanced search" to choose the suitable images.
> 
> 如何从ADNI官网下载数据，已经获取相关下载权限，但不知道如何选择检索条件获取数据图片 ![屏幕截图 2024-03-14 125635](https://private-user-images.githubusercontent.com/96705800/312704454-20b7c50f-b30b-4228-a333-40465b475669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MDQwMjAsIm5iZiI6MTcxMzYwMzcyMCwicGF0aCI6Ii85NjcwNTgwMC8zMTI3MDQ0NTQtMjBiN2M1MGYtYjMwYi00MjI4LWEzMzMtNDA0NjViNDc1NjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDA5MDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMzAzMGNhM2YxOTQyZmE4ZDg5MWIwMmJlOWE3ZmYwOWYxNjdjNjliMDFhM2EyNzcxMGQyNmMwOTFiY2M2YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wPrYKsGp5wPx72wukDH-r6P4sF3ObEK6faL8GRa95Eg)

请问你会了吗
